create sequence author_id_seq start with 1 increment by 1;
create sequence graphicnovel_id_seq start with 1 increment by 1;
create sequence library_content_id_seq start with 1 increment by 1;
create sequence library_id_seq start with 1 increment by 1;
create sequence library_serie_content_id_seq start with 1 increment by 1;
create sequence review_id_seq start with 1 increment by 1;
create sequence role_id_seq start with 1 increment by 1;
create sequence serie_id_seq start with 1 increment by 1;
create sequence users_id_seq start with 1 increment by 1;
create table author (id bigint not null, biography varchar(255), birthdate date, creation_date timestamp, creation_user varchar(255), decease_date date, external_id varchar(255), firstname varchar(255), is_scraped boolean, last_update_date timestamp, last_update_user varchar(255), lastname varchar(255), nationality varchar(255), nickname varchar(255), photo_url varchar(255), scrap_url varchar(255), site_url varchar(255), primary key (id));
create table graphicnovel (id bigint not null, back_cover_picture_url varchar(255), back_cover_thumbnail_url varchar(255), collection varchar(255), cover_picture_url varchar(255), cover_thumbnail_url varchar(255), creation_date timestamp, creation_user varchar(255), external_id varchar(255), external_id_original_publication varchar(255), book_format varchar(255), graphic_novel_url varchar(255), info_edition varchar(255), is_broche boolean, is_integrale boolean, is_original_edition boolean, is_scraped boolean, isbn varchar(255), last_update_date timestamp, last_update_user varchar(255), num_edition varchar(255), page_thumbnail_url varchar(255), page_url varchar(255), publication_date date, publisher varchar(255), reedition_url varchar(255), release_date date, scrap_url varchar(255), title varchar(255), tome varchar(255), total_pages integer, serie_id bigint, primary key (id));
create table graphicnovel_author (author_id bigint not null, graphicnovel_id bigint not null, role varchar(255) not null, primary key (author_id, graphicnovel_id, role));
create table library (id bigint not null, description varchar(255), name varchar(255), primary key (id));
create table library_content (id bigint not null, creation_date timestamp, creation_user varchar(255), is_favorite boolean, is_numeric boolean, is_physical boolean, last_update_date timestamp, last_update_user varchar(255), local_storage varchar(255), graphicnovel_id bigint, library_id bigint, primary key (id));
create table library_serie_content (id bigint not null, creation_date timestamp, creation_user varchar(255), is_favorite boolean, last_update_date timestamp, last_update_user varchar(255), library_id bigint, serie_id bigint, primary key (id));
create table review (id bigint not null, comment varchar(255), score integer, library_content_id bigint, library_serie_content_id bigint, primary key (id));
create table role (id bigint not null, name varchar(255), primary key (id));
create table serie (id bigint not null, categories varchar(255), creation_date timestamp, creation_user varchar(255), external_id varchar(255), is_scraped boolean, langage varchar(255), last_update_date timestamp, last_update_user varchar(255), origin varchar(255), page_thb_url varchar(255), page_url varchar(255), scrap_url varchar(255), site_url varchar(255), status varchar(255), synopsys varchar(255), title varchar(255), primary key (id));
create table users (id bigint not null, email varchar(255), last_login_date timestamp, password varchar(255), username varchar(255), role_id bigint, primary key (id));
create table users_library (users_id bigint not null, library_id bigint not null, primary key (users_id, library_id));
alter table graphicnovel add constraint serie_id foreign key (serie_id) references serie;
alter table graphicnovel_author add constraint author_id foreign key (author_id) references author;
alter table graphicnovel_author add constraint graphicnovel_id foreign key (graphicnovel_id) references graphicnovel;
alter table library_content add constraint graphicnovel_id2 foreign key (graphicnovel_id) references graphicnovel;
alter table library_content add constraint library_id foreign key (library_id) references library;
alter table library_serie_content add constraint library_id2 foreign key (library_id) references library;
alter table library_serie_content add constraint serie_id2 foreign key (serie_id) references serie;
alter table review add constraint library_content_id foreign key (library_content_id) references library_content;
alter table review add constraint library_serie_content_id foreign key (library_serie_content_id) references library_serie_content;
alter table users add constraint role_id foreign key (role_id) references role;
alter table users_library add constraint library_id3 foreign key (library_id) references library;
alter table users_library add constraint users_id foreign key (users_id) references users;
